name: "Tests"

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ["12", "14", "16", "17"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run lint
        if: ${{ matrix.os != 'windows-latest'}}
        run: npm run lint

      - name: Run tests
        run: npm test
